spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql:3306/catlogdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  environment: test

logging:
  level:
    root: WARN
